version: '3'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./image_vector.csv:/app/image_vector.csv
